apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: elasticplayground
spec:
  rules:
    - host: elasticplayground.local
      http:
        paths:
          - backend:
              service:
                name: elasticsearch
                port:
                 number: 9200
            pathType: Prefix
            path: "/api(/|$)(.*)"
          - backend:
              service:
                name: cerebro
                port:
                  number: 9000
            pathType: Prefix
            path: "/cerebro(/|$)(.*)"
          - backend:
              service:
                name: kibana
                port:
                  number: 5601
            pathType: Prefix
            path: "/kibana(/|$)(.*)"