apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/rewrites: "serviceName=elasticsearch rewrite=/;serviceName=cerebro rewrite=/;serviceName=kibana rewrite=/kibana"
#    nginx.ingress.kubernetes.io/use-regex: "true"
#    kubernetes.io/rewrite-target: /$2
  name: elasticplayground
spec:
  ingressClassName: nginx
  rules:
     - http:
        paths:
          - backend:
              service:
                name: elasticsearch
                port:
                 number: 9200
            pathType: Prefix
            #path: "/api(/|$)(.*)"
            path: "/api"
          - backend:
              service:
                name: cerebro
                port:
                  number: 9000
            pathType: Prefix
            #path: "/cerebro(/|$)(.*)"
            path: "/cerebro"
          - backend:
              service:
                name: kibana
                port:
                  number: 5601
            pathType: Prefix
            path: "/()(kibana/?.*)"
       host: elasticplayground.capi.gutools.co.uk