apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: elasticsearch
    tier: data
  name: elasticsearch-data
spec:
  replicas: 5
  selector:
    matchLabels:
      service: elasticsearch
      tier: data
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        service: elasticsearch
        tier: data
        iteration: "1"
    spec:
      containers:
        - image: elasticsearch:7.17.5
          name: esdata
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            limits:
              memory: 4Gi
              cpu: 1000m
          livenessProbe:
            tcpSocket:
              port: 9300
            failureThreshold: 2
            timeoutSeconds: 10
            periodSeconds: 5
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              port: 9200
              path: /
            successThreshold: 2
            failureThreshold: 2
            timeoutSeconds: 10
            periodSeconds: 5
            initialDelaySeconds: 30
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esdata
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              name: esdata-config
            - mountPath: /usr/share/elasticsearch/config/log4j2.properties
              subPath: log4j2.properties
              name: esdata-config
            - mountPath: /data/capi_snapshots
              name: snapshots
              readOnly: true
      volumes:
        - name: esdata-config
          configMap:
            name: esdata-config
        - name: snapshots
          hostPath:
            path: /data/capi_snapshots
  volumeClaimTemplates:
    - metadata:
        name: esdata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi